repos:
  - repo: local
    hooks:
      - id: check-spdx-license
        name: Check SPDX license tag
        entry: |
          bash -c '
          missing=$(rg --files-without-match "SPDX-License-Identifier: GPL-3.0-or-later" -g "*.{c,cc,cpp,cxx,h,hh,hpp,txt,cmake,yml,yaml}" -g "CMakeLists.txt" -g "Dockerfile" -g "Dockerfile.*" src tests || true)
          if [ -n "$missing" ]; then
            echo "Files missing SPDX-License-Identifier: GPL-3.0-or-later:"
            echo "$missing"
            exit 1
          fi
          '
        language: system
        pass_filenames: false
